//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestETFsByTD.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BestETFsByTD.Resources.AppStrings", typeof(AppStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All World.
        /// </summary>
        public static string AllWorld {
            get {
                return ResourceManager.GetString("AllWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. T.D..
        /// </summary>
        public static string AvgTrackingDifference {
            get {
                return ResourceManager.GetString("AvgTrackingDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed.
        /// </summary>
        public static string Developed {
            get {
                return ResourceManager.GetString("Developed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disclaimer: Data, estimates, returns, simulations and calculations provided may contain errors, inaccuracies or simplifications and are not guaranteed, nor necessarily up‑to‑date or accurate. Before making any investment, independently assess the risks and consult a qualified professional..
        /// </summary>
        public static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emerging.
        /// </summary>
        public static string Emerging {
            get {
                return ResourceManager.GetString("Emerging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider only T.D. since:.
        /// </summary>
        public static string FilterETFYear {
            get {
                return ResourceManager.GetString("FilterETFYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string ReplicationFull {
            get {
                return ResourceManager.GetString("ReplicationFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybrid.
        /// </summary>
        public static string ReplicationHybrid {
            get {
                return ResourceManager.GetString("ReplicationHybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling.
        /// </summary>
        public static string ReplicationSampling {
            get {
                return ResourceManager.GetString("ReplicationSampling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synthetic.
        /// </summary>
        public static string ReplicationSynthetic {
            get {
                return ResourceManager.GetString("ReplicationSynthetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replication Type.
        /// </summary>
        public static string ReplicationType {
            get {
                return ResourceManager.GetString("ReplicationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ETF category.
        /// </summary>
        public static string SelectETFCategory {
            get {
                return ResourceManager.GetString("SelectETFCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countrary to the common definition, to better express the data here, the tracking difference is positive when the fund outperforms the index; otherwise, negative..
        /// </summary>
        public static string TableExplanation {
            get {
                return ResourceManager.GetString("TableExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Difference by year.
        /// </summary>
        public static string TrackingDifferenceByYear {
            get {
                return ResourceManager.GetString("TrackingDifferenceByYear", resourceCulture);
            }
        }
    }
}
